src/lists/urls.py
# from django.contrib import admin
from django.urls import path
from lists import views
# from lists.views import home_page

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/",
         views.view_list, name="view_list"),
    path("<int:list_id>/add_item", views.add_item, name="add_item"),
]

src/superlists/urls.py
# from django.contrib import admin
from django.urls import include, path
from lists import views as list_views
# from lists.views import home_page

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path("", list_views.home_page, name="home"),
    path("lists/", include("lists.urls")),

]

src/lists/models.py
from django.db import models

# Create your models here.


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

src/lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from django.http import HttpResponse

# Create your views here.
# home_page = None


# def home_page(request):
#     return HttpResponse("<html><title>To-Do lists</title></html>")

# def home_page(request):
#     if request.method == "POST":
#         return HttpResponse("You submitted: " + request.POST["item_text"])

#     return render(request, "home.html")

def home_page(request):
    # if request.method == "POST":
    #     Item.objects.create(text=request.POST["item_text"])

    # item = Item()
    # item.text = request.POST["item_text"]
    # item.save()
    # return redirect(request, "home.html")
    # items = Item.objects.all()
    # return render(request, "home.html", {"items": items})
    return render(request, "home.html")


def view_list(request, list_id):
    our_list = List.objects.get(id=list_id)
    # items = Item.objects.filter(list=our_list)
    return render(request, "list.html", {"list": our_list})


def new_list(request):
    nulist = List.objects.create()
    Item.objects.create(text=request.POST["item_text"], list=nulist)
    return redirect(f"/lists/{nulist.id}/")

    # return render(
    #     request,
    #     "home.html",
    #     {"new_item_text": request.POST.get("item_text", "")},
    # )


def add_item(request, list_id):
    our_list = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=our_list)
    return redirect(f"/lists/{our_list.id}/")

src/lists/templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <title>To-Do lists</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container">

            <div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
              <div class="col-lg-6 text-center">
                <h1 class="display-1 mb-4">{% block header_text %}{% endblock %}</h1>

                <form method="POST" action="{% block form_action %}{% endblock  %}">
                    <input 
                    class="form-control form-control-lg"
                    name="item_text" 
                    id="id_new_item" 
                    placeholder="Enter a to-do item" 
                    />
                    {% csrf_token %}
                </form>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                {% block table %}
                {% endblock  %}
            </div>
        </div>
    </div>
        
    </body>
</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

{% block table %}
  <table class="table" id="id_list_table">
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}

{% comment %} <html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="POST" action="/lists/{{ list.id }}/add_item">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>
        <table id="id_list_table">
            {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
            {% endfor %}
        </table>
    </body>
</html> {% endcomment %}